# (PART) Course content {.unnumbered}

# Hello world {#hello-world}

We will start by showing you what is possible at the end of the class and running a reasonably complex visualization code in your environment.
The goal of this `Hello world` part is not to make you understand every bit of the code but instead to make you hungry for more.
We aim for you to code such a visualization from scratch at the end of our course.
To reach that goal, we will --- step by step --- introduce you to the most relevant facets of Data Science with R and the Tidyverse.

::: rstudio-cloud
The Posit Cloud (formerly RStudio Cloud) workspace containing the application exercises is [here](https://posit.cloud/spaces/322662).
If you haven't already registered for Posit Cloud and joined the workspace, please do so now.
Be sure to register through the link sent to you via e-mail since we purchased a Posit Cloud premium version for this course.
:::

## Slides, application exercises, and references

::: slide-deck
**Unit 1 - Deck 1: Welcome**

::: slides
[Slides](https://lukas-jue.github.io/intro-tidyverse-2023-january/slides/u1-d01-welcome/u1-d01-welcome.html#1)
:::
:::

::: application-exercise
**Your first data visualization: UN Votes**

Please open your Posit Cloud for this exercise.

::: source
[Source](https://github.com/lukas-jue/intro-tidyverse-2023-january/blob/master/docs/application-exercises/ae-01a-un-votes/unvotes.Rmd)
:::
:::

::: slide-deck
**Unit 1 - Deck 2: Meet the toolkit --- Programming**

::: slides
[Slides](https://lukas-jue.github.io/intro-tidyverse-2023-january/slides/u1-d02-toolkit-r/u1-d02-toolkit-r.html)
:::

::: reading
-   R4DS :: [Chp 2 - Introduction](https://r4ds.had.co.nz/explore-intro.html)
-   IMS :: [Sec 1.1 & 1.2 - Case study & Data basics](https://openintro-ims.netlify.app/getting-started-with-data.html#basic-stents-strokes)
:::
:::

::: application-exercise
**The Bechdel Test + R Markdown**

Please open your Posit Cloud for this exercise.

::: source
[Exercise template](https://github.com/lukas-jue/intro-tidyverse-2023-january/blob/master/docs/application-exercises/ae-02-bechdel-rmarkdown/bechdel.Rmd)
:::

::: source
[Solution, `.Rmd` file](https://github.com/lukas-jue/intro-tidyverse-2023-january/blob/master/docs/application-exercises/ae-02-bechdel-rmarkdown/bechdel-solution.Rmd)
:::

::: reading
This exercise uses data from the following FiveThirtyEight story on the [Bechdel Test](https://en.wikipedia.org/wiki/Bechdel_test):

Hickey, W.
(2014, April 1): [The Dollar-And-Cents Case Against Hollywood's Exclusion of Women](https://github.com/lukas-jue/intro-tidyverse-2023-january/blob/master/docs/application-exercises/ae-02-bechdel-rmarkdown/bechdel.Rmd), *FiveThirtyEight.com*
:::
:::
