# (PART) Next steps {.unnumbered}

# Things you can do after this course

### Continue this course {.unnumbered}

This course is based on Data Science in a Box by Mine Çetinkaya-Rundel.
Due to time constraints, we were only able to show you the most important aspects.
If you want to continue with this course, you can access many more lecture materials (including recorded videos, interactive tutorials, and exercises) at [datasciencebox.org](https://datasciencebox.org/).

### Join TechAcademy e.V. {.unnumbered}

TechAcademy e.V.
is a student organization at Goethe University educating students in Data Science with R or Python as well as Web Development.
Students of all academic subjects can develop coding skills through the Data Science and Web Development programs.

You're course instructors are part of the organization's management team.
Feel free to join us either as students for one of our programs (in the beginning of each semester) or as part of our voluntary team.
Find more information on [tech-academy.io](https://tech-academy.io/).

### Join the Campus useR Group in Frankfurt {.unnumbered}

There's a quite active R community in Frankfurt that meets once a month.
It's open for students, professors, industry practitioners, journalists, and all people that love to use R.
In those meetings, you'll hear about other's work, discuss new developments, and ask questions.
All levels of expertise are welcome.
Check it out on [Meetup](https://www.meetup.com/r-frankfurt/).

### Follow the R Community {.unnumbered}

The R community is very friendly, helpful, and engaging.
For example, follow `#rstats` on Twitter and you will see many great use cases, new developments, and a bunch of tips and tricks that you have never heard of before.

### Install R and RStudio locally {.unnumbered}

If you used RStudio Cloud so far, the next step should be to set everything up on your local computer.
RStudio Cloud is great for getting started with R without having to worry about installing anything locally.
For bigger projects, though, you should set up R and RStudio Cloud in your own environment.

### Version Control with Git {.unnumbered}

If you're serious about data science, you will need Git.
Better learn it early and start enjoying and appreciating it before it's too late and you're pressured into learning it on the fly!
Every project you do should be versioned with Git.
Regardless if you're working alone or with a big group of developers.
Regardless if you write ten lines of code or a really complex program.
With Git, you can keep track of all your changes.
It's like a Dropbox/Google Drive for developers, but way better.
Pro-Tip: Get free GitHub Pro as a student with the [GitHub Student Developer Pack](https://education.github.com/pack).

RStudio has a nice interface that lets you enjoy the perks of Git without ever having to touch the command line -- sounds great, does it?
Learn how to set up the Git & R workflow with [Happy Git with R](https://happygitwithr.com/).

### R Graph Gallery {.unnumbered}

Get inspiration to take your plotting to the next level at the [R Graph Gallery](https://www.r-graph-gallery.com/) Includes code to reproduce the plots.

### See what else is possible in R {.unnumbered}

R and RStudio are powerful tools to do many things beyond traditional Data Science.
For example, all course materials (including the website and slides) were written in R Markdown.
You can also write your entire doctoral thesis in R Markdown tools without ever leaving RStudio.
Everything from data analysis to results communication can be implemented and connected such that you never have to manually paste tables and figures to a Word document.
You can find many useful references at [RStudio Education](https://education.rstudio.com/).
